### ISSUE TITLE
Signed exe

### ISSUE THREAD

**Issue by dark-spark** [cntools/cnping#100]
Is there a possibility of getting a signed exe created? I have tried self-signing on windows with no luck so far, I think I am using the wrong type of certificate, I haven't done it before. I am probably the only one using this on windows so I know it's unlikely, but I thought I would ask.

**Comment by dreua** [comment]
Would a self signed certificate actually help? It should be possible but not sure it is worth the effort.

I think an actual certificate would cost about 150 Eur/USD per year and afaik that isn't directly all green and trusted but it takes some time to become well known. Given the small user base this might actually never happen, I wonder whether the actual rules and and numbers are published or Microsofts secret.

(Finally we would need to renew the cert every other year or so and sign it with the new and old cert and hope again that the usage is enought that the new cert becomes well known before the cold one expires.)

I'm not sure what your use case is, but would probably need some research to make sure signing the exe would actually solve it.

**Comment by dark-spark** [comment]
Thanks, I thought that might be the case. 

I use it on a work machine, and it is being flagged as malicious by Crowdstrike. We were hoping that signing it will fix the issue.

I will try again with the self-signing and see how I go, but I agree that it might not be enough.

**Comment by dreua** [comment]
Can you submit the exe to Crowdstrike for analysis, maybe they can flag it as false positive?

How does Crowdstrike deal with stuff that you compiled yourself? Cnping can easily be compiled on wsl for example, or in a Docker container. Let me know in case you need help with that.

(This reminds me how lucky I am to have a Linux desktop at work :))

**Comment by dark-spark** [comment]
That is a good idea. I will see if I can submit it to Crowdstrike. 

I have compiled this exe on WSL on this machine, it still gets flagged, I assume it is just the signing it is worried about. 

I'd love to run Linux on my machine here, but I work in Industrial Control, not many options for Linux versions of the software I need.

**Comment by dreua** [comment]
Do you have someone who develops software for Windows in the compoany? They'll have that very problem with each version they compile, won't they? There must be some way to allow software development, i.e. compiling and running an exe.

**Comment by dreua** [comment]
Any news? Let me know if you really need this signed, maybe we can work something out.

**Comment by dark-spark** [comment]
Work don't have a cert I can use and I couldn't get the self signing to work either. They can't confirm if signing will fix the issue in Crowdstrike, I can't see why they can't just allow list it and move on. 

I am happy to close this off mate, don't want anyone going out of their way as it may not solve the issue.

**Comment by dreua** [comment]
Thanks for the follow up!

**Comment by dreua** [comment]
Just got another idea: Can you run the Linux version of cnping inside wsl? I've never tried it but GUI tools but it should be supported in the latest wsl, according to Microsoft:
https://learn.microsoft.com/en-us/windows/wsl/tutorials/gui-apps
