### ISSUE TITLE
Building .exe with Travis CI

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#32]
Hey,
I wanted to learn how Travis CI works and cnping came in handy as a test subject: I managed to build it on their servers and as a bonus upload the .exe to the [releases page.](https://github.com/dreua/cnping/releases) (The exe works on Windows 10 as expected.)

If you want to integrate this in your main branch you have to sign up to Travis CI (which is free and really easy) and take my [.travis.yml](https://github.com/dreua/cnping/blob/travis-integration/.travis.yml) and customize it to your repository. (change api_key.secure, repo and branch)

I am not sure if this is worth the effort so please feel free to just close this in case you are not interested. I can provide more information, links and help if needed.

**Comment by cnlohr** [comment]
What is the API key?

This does look very cool.

**Comment by dreua** [comment]
Travis needs a Github API key for the access rights to upload files (they call it assets) to your projects releases page on Github. 
See https://docs.travis-ci.com/user/deployment/releases/#Authenticating-with-an-OAuth-token for more information. I [installed the Travis client](https://github.com/travis-ci/travis.rb#installation) and used the `travis setup releases` command to automate the creation and encryption of the needed key. (The .travis.yml file is part of your public repository so the Github API key must be stored encrypted with a public key from Travis, so only the Travis servers can decrypt and use it to upload the files back to Github.)

**Comment by cnlohr** [comment]
Now I just have to figure out how to mark issues unread so I can try to get this tomorrow.

**Comment by dreua** [comment]
Maybe another comment will do?

**Comment by cnlohr** [comment]
@dreua Are you interested in taking over cnping?

**Comment by dreua** [comment]
Well yeah, I was actually thinking about asking you about this when I was worried that you might not be interested or have the time to look after this project any more. 
I think I could take care of this issue, the versioning, maybe the makefile (#61), then finish the Fedora packaging, small issues and pull requests that might come in and stuff like this. To be honest though, for bigger work like an Android release or IPv6 support I currently lack the time that I would need to write this in C.
That being said, I'd really like to keep this project alive as it's not only very useful for me but also my first Open Source contribution. (Yes, you got my into this via Youtube! Thanks by the way ;))
What exactly do you mean by taking over? (Repository access, fork, Github group...?)
Looking forward to hearing from you!

**Comment by cnlohr** [comment]
I totally forgot that I could make collaborators.  You should be able to do whatever you need to do in my repo now.   I was originally thinking that it would be more along the lines of you making dreua/cnping and I have a note saying "it's there now" but I really think I'm going to be able to get back into more of the open source stuff.
