### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#39]
I'm not sure how much work this is, but it would be a nice addition and it will be needed some day...

**Comment by cnlohr** [comment]
I'm pretty confident the IPv6 thing is just a fad and is gonna blow over eventually.  Maybe there will be a new IP standard that isn't excessively complicated people will actually use.

(ok, joking, a little bit)

I don't really understand the functions surrounding IPv6 especially in regards to how things like ping work.  If you're up for integrating and testing it I would be up for accepting a pull request.

**Comment by dreua** [comment]
Yeah, rethinking this now I guess you are right and it's not worth it at the moment. Should we close this for now or should we leave it open in case someone with great IPv6-skills comes by looking for a way to put them to good use?

**Comment by dreua** [comment]
Done by @mrbesen , thank you!
