### ISSUE TITLE
Making a release

### ISSUE THREAD

**Issue by jcgruenhage** [cntools/cnping#60]
Hey, could you start adding git tags with some kind of a versioning scheme? I'd like to package this for voidlinux, but they don't accept packages without versions. This would also be a requirement for a bunch of other distros, as mentioned in #49.

**Comment by jcgruenhage** [comment]
See https://github.com/void-linux/void-packages/pull/13627

**Comment by cnlohr** [comment]
@jcgruenhage @dreua   I am a-ok with this. I've never implemented versioning for that sort of thing.  What kinds of steps would we use to do a versioning scheme?  I am back to doing some github stuff after working insane hours at my new job for about 8 months.

**Comment by cnlohr** [comment]
Should we push for 1.0-pre then?  And have you guys test it?

**Comment by jcgruenhage** [comment]
In my testing, cnping has worked flawlessly. I;d be happy to see this declared as 1.0, anyone else got an opinion on that? A non-pre release is a blocker at least for the voidlinux package

**Comment by dreua** [comment]
I would prefer 1.0.0 to be more in line with semver. No other objections.

**Comment by dreua** [comment]
I can integrate Travis ci and release 1.0.0 after work, i.e. in about 10 hours.

**Comment by dreua** [comment]
1.0.0 is out, let me know if there is anything else.
