### ISSUE TITLE
Support ARM architectures

### ISSUE THREAD

**Issue by jcgruenhage** [cntools/cnping#61]
https://travis-ci.org/void-linux/void-packages/builds/570995593 shows how the builds fail on ARM.

**Comment by dreua** [comment]
Aarch64 build for fedora [just succeeded](https://copr-be.cloud.fedoraproject.org/results/dreua/cnping/fedora-rawhide-aarch64/01005092-cnping/) but be aware that I can't test if the executable actually runs. 

Looking at your aarch64 build, the last call of gcc instead of aarch...gcc might be wrong:

```
aarch64-linux-gnu-gcc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv8-a   -I/usr/aarch64-linux-gnu/usr/include -g -Os -I/opt/X11/include -Wall     -c -o httping.o httping.c

gcc -fstack-clash-protection -D_FORTIFY_SOURCE=2 -O2 -pipe -march=armv8-a   -I/usr/aarch64-linux-gnu/usr/include -g -Os -I/opt/X11/include -Wall -o cnping cnping.o CNFGFunctions.o CNFGXDriver.o os_generic.o ping.o httping.o -lX11 -lm -lpthread -g -L/opt/X11/lib/ 

[Ld errors here]
```

Maybe we need to change the Makefile to use the compiler given by the environment. Not sure how to do this, though.

**Comment by dreua** [comment]
Fixed some stuff here, but there is more to do: https://github.com/void-linux/void-packages/pull/13725

**Comment by cnlohr** [comment]
@dreua feel free to make a PR for this addition to the Makefile with a conditional compile.

**Comment by cnlohr** [comment]
@dreua What is wrong with the existing Makefile for this if CC is overridden going into the Makefile?  I.e. why the stack clash protection and fortify source flags?  Could they be added to the regular makefile?

**Comment by dreua** [comment]
Well, I just tried to make it work some way. I didn't add extra flags, just tried to keep what was there while making it possible for the packaging environment to overwrite and customize stuff:

1) Replace direct call to `gcc` by `$(CC)` with a default value of `gcc`, so running make locally will continue to work while you can overwrite CC for cross compilation by appending it to the make command. I think this change should stay and will provide a pull request for it.
2) The changes I made to the C- and LDFLAGS should be discarded as they didn't work in the end. I just found out that [pgk-config](https://danyspin97.org/blog/makefiles-best-practices/#---no-anchors---you-need-to-manually-search-for---pkg-config----) might be a better way include the X11 libs, if not the solution for the void-linux package. Looking into this...

**Comment by cnlohr** [comment]
I've committed, but I think the right way would be to use the `?=` operator in the `Makefile` to override various behavior.  I think that should include CFLAGS and LDFLAGs.

**Comment by dreua** [comment]
Back to topic: The package builds now on all plattforms. I just [updated and added a dependency](https://github.com/void-linux/void-packages/pull/13725/commits/ec5bae3db4242bff0bbae8e22a401c3af58b2e1c) in the end.

**Comment by jcgruenhage** [comment]
Sure, looking good. Thank you!

**Comment by jcgruenhage** [comment]
rebased onto master, squashed the two commits and fixed the commit message. PR now at https://github.com/void-linux/void-packages/pull/14805

**Comment by cnlohr** [comment]
@jcgruenhage I left a comment over there.  I've never done it before, how would I go about pulling from there back onto cnping?
