### ISSUE TITLE
Get version string from git

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#66]
I think this is the best way: https://stackoverflow.com/a/12368262/4529404
I will do some tests and implement it when I get the time.

**Comment by cnlohr** [comment]
Do we really want a git version string instead of a human-readable incrementing one?  I figured most distros would want cnping-1.0, etc. or cnping=1.0

**Comment by dreua** [comment]
Well, I hope that it doesn't use the git hash but returns us the version tag instead, so that would be human readable and doesn't require you to set the version in the source code each time you build/release. I'll try that now...
