### ISSUE TITLE
Windows Options Dialog Text is cut off

### ISSUE THREAD

**Issue by CaiB** [cntools/cnping#69]
When running cnping without command-line options on Windows, a dialog is presented to configure the options instead. On my machine, the text looks unusually large (I'm using 100% display scaling, default text sizes, etc). This causes the text to get cut off on the right, and since the window is not resizable, this makes a lot of the options unreadable.

![image](https://user-images.githubusercontent.com/6701127/81039681-aaf39800-8ee4-11ea-9856-a8f9aa709cb5.png)

**Comment by dreua** [comment]
For comparison, here is what it looks like on my Windows 10:
![Annotation 2020-05-05 213537](https://user-images.githubusercontent.com/15114715/81108253-b365c600-8f18-11ea-81f3-e48cb5186733.png)
It's exactly the same and a few pixels less in height. And of course a different font that fits. Maybe we can make the Window resizable - automatically fitting the contents in best case.

**Comment by CaiB** [comment]
Ah, it’s possible that Windows is selecting a different font that is able to display Japanese characters, since my system is partially set to Japanese language mode. It looks like this font simply has larger characters for English characters, hence cutting off the text.

**Comment by dreua** [comment]
I see, so it may be better to set the font instead of making the window resizable? At the moment no font is set to it must take some Windows default, but iirc setting a font is easily possible. Maybe we can even go for a fixed width font like the console uses so the indentation is preserved.

**Comment by dreua** [comment]
The dialog is now resizable (Fixed in #70)
