### ISSUE TITLE
Info: rawdraw was recently changed to submodule - Readme if you have checked out this repo before May 2020

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#73]
Here is how I fixed it, maybe not the best way:
`git pull` or `git pull upstream master` (whatever you need to get the latest cnping)
```
rm -rf rawdraw/
git submodule init
git submodule update
```

**Comment by dreua** [comment]
Fixes this error:
```
$ make all
cc -s -Os -I/opt/X11/include -Wall -o cnping cnping.c ping.c httping.c -lX11 -lm -lpthread -s -L/opt/X11/lib/
cnping.c:28:10: fatal error: rawdraw/os_generic.h: No such file or directory
   28 | #include "rawdraw/os_generic.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
ping.c:183:10: fatal error: rawdraw/os_generic.h: No such file or directory
  183 | #include "rawdraw/os_generic.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
httping.c:25:10: fatal error: rawdraw/os_generic.h: No such file or directory
   25 | #include "rawdraw/os_generic.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:37: cnping] Error 1

```

**Comment by cnlohr** [comment]
Wait... what?  Why are there multiple definitions?  It should have been marked static for a while now?

**Comment by dreua** [comment]
Ah, sorry about the confusion: No, this has nothing to do with the `make all` at all :wink:. The problem here is that a regular `git pull` does not update the rawdraw directory to become a submodule and be checked out at the correct commit so the rawdraw directory's contents get deleted as you deleted them in 5851251703721b5bec5e5c94bfbf93ca1a7ad6d5 (which is good) but then it stays empty and the includes stop working. This should just be a friendly reminder, that people need to init and update the submodule. (The rm step may be not needed actually.)

**Comment by cnlohr** [comment]
Then this issue shall remain open.
