### ISSUE TITLE
cnping shows up as "Unknown" without icon in Gnome's Task Switcher

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#75]
This screenshot is already with a fix applied, previously it just displayed "Unknown". We can at least set the name by re-using some previously commented code in rawdraw. I think this would need an interface in rawdraw, to set the window class name to the desired value. I'm not sure how if and how this should be added to the rawdraw API so tell me what you think. 

![cnping_task_switcher](https://user-images.githubusercontent.com/15114715/90129098-4dcf7400-dd68-11ea-88bb-b0266ba40274.png)

Here's the code to change: https://github.com/cntools/rawdraw/blob/2eeb8a650d54232d895b1259f4b0ff83850dac9a/CNFGXDriver.c#L147-L162

### Icon
From what I just read on that topic, we would need to install a .desktop file so that Gnome can match the executable to it and use the icon specified there. And we would need an actual icon of course ;)

**Comment by cnlohr** [comment]
That seems very strange. Isn't there some other atom mechanism?
