### ISSUE TITLE
Current master version doesn't work on Windows 10 (VM)

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#83]
Working on #82 I stumbled upon this other bug.

Something somewhere introduced a change that makes cnping just show up with a grey frame on my Windows 10 VM. It stays like that and quits after some time

Some bisecting later, I'm quite sure it is https://github.com/cntools/rawdraw/commit/8801832a8d2bbbca4d11f62cde91eb72b37ad555

Can someone provide more data points, like whether it does or doesn't work for you?

**Comment by dreua** [comment]
Here is the current exe (6b89363e6b79ecbf612306d42a8ef94a5a2f756a) because CI is broken, use at your own risk.
[cnping.zip](https://github.com/cntools/cnping/files/6270127/cnping.zip)

**Comment by dreua** [comment]
Works on bare metal, probably an issue with OpenGL on my VM.
Related: https://github.com/cntools/rawdraw/issues/55 - Maybe I should put some more work into that.

**Comment by dreua** [comment]
Can't reproduce this right now, closing until someone can.

**Comment by mrbesen** [comment]
as mentioned here: https://github.com/cntools/cnping/pull/87#issuecomment-1255200444

i had the same problem.
I think its about some opengl support in rawdraw or something. But i dont know if we even should care. Its only on windows inside a vm, so is it even worth?

**Comment by dreua** [comment]
> Its only on windows inside a vm, so is it even worth?

I agree. I may debug it in case it hits me again but won't set up a VM just to reproduce it.
