### ISSUE TITLE
Every other HTTP ping has a very low (wrong) value for some servers

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#84]
This depends on the webserver or its configuration, but you can easily find examples, including homerouters or ESP8266s, which reproduce this behavior. I think it has something to do with reusing connections or failure to do so. The ping response values are ridiculously low, probably rather some runtime until the error occurs than an actual ping.

![Screenshot_20210606_112425](https://user-images.githubusercontent.com/15114715/120919497-3a581580-c6ba-11eb-8f93-be27e42cd019.png)

**Comment by cnlohr** [comment]
I've also noticed this and don't know the cause.

**Comment by mrbesen** [comment]
I had just an idea what this could be: The Nagle Algorithm.
Thats part of TCP and only sends a tcp-fragment when a tcp fragment has enough data. This is to reduce overhead.
So the first ping gets "send" (written to the buffer)
Second ping gets "send" (written to the buffer -> buffer full enough -> fragment get send for real)
Both pings get answered in the same returning fragment. So then the calculation is maybe a bit off and gets confused.

To disable the Nagle Algorithm `TCP_NODELAY` flag need to be set with `setsocketopt`. I havent checked the code if it is already set, maybe i'm looking at this problem in the wrong way.

**Comment by dreua** [comment]
Thank you for fixing this, @mrbesen !
