### ISSUE TITLE
New Icon?

### ISSUE THREAD

**Issue by mrbesen** [cntools/cnping#90]
Hey, i made a new icon for cnping.
(party because i didn't saw an icon on my setup and thought there was none. But i think i just messed up the install)

What do you guys think? Should this simplified icon replace the current one?
Its an svg. So its scaleable and can be exported to every required size as png. But AFAIK most distros prefer svg anyways.
![cnping_icon](https://user-images.githubusercontent.com/8640309/204141677-593af5b1-e1d6-40ac-9772-58003a359853.svg)

**Comment by cnlohr** [comment]
I'm not sure how to add icons in this context?

**Comment by mrbesen** [comment]
As application icon. (The icon you see in the taskbar and when you search for cnping)

The current icon lives here: [/freedesktop/icons/hicolor](/cntools/cnping/tree/master/freedesktop/icons/hicolor)

**Comment by dreua** [comment]
Looks good to me, certainly better then my screenshot ;)

**Comment by dreua** [comment]
Would you like to create a PR to replace it?
Applying it to the application is another topic, I remember toying around with. It should work with the desktop file and the icons at the right path and setting the correct wm_class or something. Probably only makes sense in a RPM or DEB package or the like, but I'd like to try that, at least for RPM.

**Comment by dreua** [comment]
Merged and done, thank you!
