### ISSUE TITLE
Warn when using https://

### ISSUE THREAD

**Issue by dreua** [cntools/cnping#93]
It would be nice to get a warning when trying to ping `https://` because as of now, it says the hostname can't be resolved. (It can't because DNS doesn't now `https://example.com`.)
I think we could catch anything containing `:` or `//` when not `http://` and warn about not supported protocol.

**Comment by cnlohr** [comment]
A side thought - could we do TLS pinging?

**Comment by dreua** [comment]
My first thought: That would probably be super easy in Go.
Second thought: is TLS ping even a thing?
First Google hit: https://github.com/airnandez/tlsping written in Go ;)

Thoughts aside, there is https://github.com/eduardsui/tlse for C so I'd say yes, we probably can, but I'm not going to do it. Any volunteers?

**Comment by cnlohr** [comment]
I've written bare metal basic outer-layer TLS stuff for QUIC a while ago.  It was only a few lines of C code.  I don't know how similar the TLS on QUIC is to TLS on https, though.

**Comment by mrbesen** [comment]
I dont think, that TLS ping is a good idea.
